---
apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: '{{ include "grafana.name" . }}-config'
data:
  grafana.ini: |
    [server]
    protocol = http
    domain   = {{ .Values.config.server.domain   }}
    root_url = {{ .Values.config.server.root_url }}
    serve_from_sub_path = true
    enforce_domain = false

    [database]
    type     = {{ .Values.config.database.type }}
    host     = {{ .Values.config.database.host }}
    name     = {{ .Values.config.database.name }}
    user     = {{ .Values.config.database.user }}
    password = {{ .Values.config.database.pass }}

    [security]
    disable_initial_admin_creation = false
    cookie_secure = true

    [users]
    allow_sign_up = false
    allow_org_create = false

    [auth.anonymous]
    enabled  = true
    org_role = Viewer
    org_name = City of Bloomington

    [log]
    mode = console

...
